### ISSUE TITLE
“Cannot read property 'type' of undefined”

### ISSUE THREAD

**Issue by hrdlnk** [one-aalam/svelte-notion-kit#1]
Returns the following error message

```shell
500
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at NotionBlock.svelte:18:15
    at Object.$$render (/private/tmp/svelte-notion-kit/node_modules/svelte/internal/index.js:1671:22)
    at PostPreview.svelte:19:28
    at Object.$$render (/private/tmp/svelte-notion-kit/node_modules/svelte/internal/index.js:1671:22)
    at eval (/private/tmp/svelte-notion-kit/src/routes/index.svelte:84:187)
    at Proxy.each (/private/tmp/svelte-notion-kit/node_modules/svelte/internal/index.js:1637:16)
    at index.svelte:41:11
    at Object.$$render (/private/tmp/svelte-notion-kit/node_modules/svelte/internal/index.js:1671:22)
    at Object.default (root.svelte:38:46)
    at eval (/private/tmp/svelte-notion-kit/src/routes/__layout.svelte:14:105)
```

**Comment by christianhturner** [comment]
I'm getting the same error.

**Comment by rdtect** [comment]
any solutions?
